#!/bin/bash

# Kill em all
killall -q polybar
# Kill em all softly
# polybar-msg cmd quit

# Wait till they're dead
while pgrep -u $UID -x polybar 2>/dev/null
do
  sleep 1
done

# Get the monitor list
monitor_list=$(polybar --list-monitors)

# Running on a laptop
is_laptop=$(echo "$monitor_list" | grep 'eDP1')
if [ ! -z "$is_laptop" ]
then
  polybar -q top 2>&1 | tee -a /tmp/polybar_top.log & disown
fi

# Running inside a VM
is_VM=$(echo "$monitor_list" | grep 'Virtual-1')
if [ ! -z "$is_VM" ]
then
  polybar -q top-VM 2>&1 | tee -a /tmp/polybar_top.log & disown
fi

# 1st external monitor (TOP-LEFT)
is_hdmi=$(echo "$monitor_list"|grep 'HDMI-0')
if [ ! -z "$is_hdmi" ]
then
  echo "Launching HDMI-0"
  polybar -q top-HDMI0 2>&1 | tee -a /tmp/polybar_top_HDMI1.log & disown
fi

# 2nd external monitor (TOP-RIGHT)
is_dp=$(echo "$monitor_list" | grep 'DP-2')
if [ ! -z "$is_dp" ]
then
  echo "Launching DP-2"
  polybar -q top-DP2 2>&1 | tee -a /tmp/polybar_top_DP2.log & disown
fi
