#!/bin/sh

#
# This script is used to change the background to a new one.
# If given a file, sets it and adds it in the wallpapers folder. Otherwise, choose a random one.
#
# Note: Chooses a random monitor between all the active ones.
#

# Path to the wallpapers
folder="${HOME}/.local/share/wallpapers/"

# If given an existing file in argument, add it to the wallpaper folder and we'll use this one.
if [ -f "$1" ] && [ ! -f "${folder}${1}" ]
then
  cp "$1" "$folder" && notify-send -i "$1" "Wallpaper added."
  to_display=$1
else
  # Else if no (or invalid) file given, choose a random one
  to_display=$(find "$folder" -type f | shuf -n 1)
fi

# Choose a random monitor to change the wallpaper only on that one
monitor=$(xrandr --listactivemonitors | grep '^ [[:digit:]]' | awk '{print $NF}' | shuf -n 1)

# Update the wallpaper on the selected monitor
xwallpaper --output "$monitor" --maximize $to_display

# Save current file name for potential removal
# TODO: Handle multiple monitor ?
echo "$to_display" > ${HOME}/.local/scripts/.currentbg

# Exit
exit 0
