#!/bin/bash

# Kill em all
killall -q polybar
# Kill em all softly
# polybar-msg cmd quit

# Wait till they're dead
while pgrep -u $UID -x polybar 2>/dev/null
do
  sleep 1
done

# Launch
monitor_list=$(polybar --list-monitors)
is_laptop=$(echo "$monitor_list" | grep 'eDP1')
if [ ! -z "$is_laptop" ]
then
  polybar -q top 2>/dev/null & disown
  has_external=$(echo "$monitor_list" | grep 'DP1-3')
  if [ ! -z "$has_external" ]
  then
    polybar -q top-DP1-3 2>/dev/null & disown
  fi
fi

# 1st external monitor (TOP-LEFT)
is_hdmi=$(echo "$monitor_list"|grep 'HDMI-0')
if [ ! -z "$is_hdmi" ]
then
  echo "Launching HDMI-0"
  polybar -q top-HDMI0 2>/dev/null & disown
fi

# 2nd external monitor (TOP-RIGHT)
is_dp=$(echo "$monitor_list" | grep 'DP-2')
if [ ! -z "$is_dp" ]
then
  echo "Launching DP-2"
  polybar -q top-DP2 2>/dev/null & disown
fi
